language: minimal
matrix:
  include:
    - os: osx
      env: DESCRIPTION=macOS
    - os: linux
      dist: xenial
      env: DESCRIPTION=Ubuntu
    - os: linux
      env:
        - DESCRIPTION=Docker(CentOS)
        - DOCKERFILE=.test/centos.Dockerfile
    - os: linux
      env:
        - DESCRIPTION=Docker(Ubuntu)
        - DOCKERFILE=.test/ubuntu.Dockerfile
script:
- |
    if [ -n "${DOCKERFILE}" ]; then
      docker build -f ${DOCKERFILE} .
    else
      ./link.sh
      ./install.sh
    fi
