language: minimal
matrix:
  include:
    - os: linux
      env:
        - DESCRIPTION=Docker(Ubuntu:devel)
        - OSIMAGE=ubuntu:devel
    - os: linux
      env:
        - DESCRIPTION=Docker(Ubuntu:rolling)
        - OSIMAGE=ubuntu:rolling
    - os: linux
      env:
        - DESCRIPTION=Docker(Ubuntu:latest)
        - OSIMAGE=ubuntu:latest
    - os: linux
      env:
        - DESCRIPTION=Docker(Ubuntu:18:04)
        - OSIMAGE=ubuntu:18:04
    - os: linux
      env:
        - DESCRIPTION=Docker(CentOS:latest)
        - OSIMAGE=centos:latest
    - os: linux
      env:
        - DESCRIPTION=Docker(CentOS:7)
        - OSIMAGE=centos:7
    - os: linux
      dist: focal
      env: DESCRIPTION=Ubuntu(Focal 20.04)
    - os: linux
      dist: bionic
      env: DESCRIPTION=Ubuntu(Bionic 18.04)
    - os: osx
      env: DESCRIPTION=macOS
script:
- |
    if [ -n "${OSIMAGE}" ]; then
      docker build --build-arg OSIMAGE=${OSIMAGE} .
    else
      ./install.sh
    fi
