version: 2
jobs:
  build:
    docker:
      - image: docker:18.06-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -f ubuntu.Dockerfile .
      - run:
          command: docker build -f centos.Dockerfile .
